services:
  - type: web
    name: enhancer-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    # Download the model if it doesn't exist, then start the bot
    startCommand: "if [ ! -f RealESRGAN_x4plus.pth ]; then wget https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth; fi && python bot.py"
    plan: free
    autoDeploy: false
